# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Azure Login_cred
      uses: azure/login@v1
      with:
        az-version: latest
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: print pwd
      run: |
          echo `pwd`
    
   
          
    - name: Deploy SQL script to Azure SQL
      uses: Azure/sql-action@v2
      with:
        connection-string: 'Server=tcp:rajeshsnpdemo1.database.windows.net,1433;Initial Catalog=RajeshDemo1;Persist Security Info=False;User ID=rajeshsnpdemo1;Password=inScott@1122;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
        path: 'TestScript.sql'

        
    - name: Display Azure Subscription Informations
      run: az account show
     
